import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Fira_Code } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const firaCode = Fira_Code({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${firaCode.variable} antialiased font-sans bg-gray-900 text-white min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
